### ISSUE TITLE
Dit element bestaat niet

### ISSUE THREAD

**Issue by Theo-denBlanken** [kgeurts/Responsive_Grid#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
.foto3{
	height: 0px;
	width: 0px;
} 
```

URL: https://github.com/kgeurts/Responsive_Grid/blob/master/css.css

Feedback: waarom schrijf er dan css voor?[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"fc333e73c992bd146affbd86b9aa0f82fdcb567b","path":"css.css","reviewer":"Theo-denBlanken"}')

**Comment by kgeurts** [comment]
Deze had ik eerst toevoegd om een extra foto bij een andere viewport toe te voegen. Deze is nu aangepast.
